const fetch = require('node-fetch');
const token = require('./keys/personal_access_token');
const url = 'https://app.asana.com/api/1.0';
const workspace_gid = '1001152499280073';

const query = (query_path, cb) => {
  return fetch(`${url}${query_path}`, {
    headers: { Authorization: `Bearer ${token}` }
  })
    .then(res => res.text())
    .then(body => cb(body));
};

const createTask = ({ assignee, projects, parent, name, notes = '' }) => {
  return fetch(`${url}/tasks`, {
    method: 'post',
    headers: { Authorization: `Bearer ${token}` },
    body: JSON.stringify({
      data: {
        assignee,
        name,
        notes: `${notes}\n\nGenerated by Asana-Task-Gen`.trim(),
        projects,
        parent,
        workspace: workspace_gid
      }
    })
  })
    .then(res => res.json())
    .then(body => body.data);
};

const addTaskToSection = (task, section) => {
  return fetch(`${url}/sections/${section}/addTask`, {
    method: 'post',
    headers: { Authorization: `Bearer ${token}` },
    body: JSON.stringify({ data: { task } })
  })
    .then(res => res.json())
    .then(body => body.data);
};

module.exports = { query, createTask, addTaskToSection };
