const fetch = require('node-fetch');
const token = require('./keys/personal_access_token');
const url = 'https://app.asana.com/api/1.0';
const workspace_gid = '1001152499280073';

const checkRes = res => {
  if (res.ok) return res.json();
  console.error(res);
  throw res.statusText;
};

const query = (query_path, cb) => {
  return fetch(`${url}${query_path}`, {
    headers: { Authorization: `Bearer ${token}` }
  })
    .then(checkRes)
    .then(body => cb(body));
};

const createTask = ({
  assignee,
  projects,
  parent,
  name,
  notes = '',
  due_on
}) => {
  return fetch(`${url}/tasks`, {
    method: 'post',
    headers: { Authorization: `Bearer ${token}` },
    body: JSON.stringify({
      data: {
        assignee,
        name,
        notes: `${notes}\n\nGenerated by Asana-Task-Gen`.trim(),
        due_on,
        projects,
        parent,
        workspace: workspace_gid
      }
    })
  })
    .then(checkRes)
    .then(body => body.data);
};

const addTaskToSection = (task, section) => {
  return fetch(`${url}/sections/${section}/addTask`, {
    method: 'post',
    headers: { Authorization: `Bearer ${token}` },
    body: JSON.stringify({ data: { task } })
  })
    .then(checkRes)
    .then(body => body.data);
};

module.exports = { query, createTask, addTaskToSection };
